linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - '.rubocop.yml'
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingBlankLines:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Metrics/LineLength:
        Max: 110
