common: &common
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost

development:
  <<: *common
  database: regulus_development
  username: development
  password: 

test:
  <<: *common
  database: regulus_test
  username: test
  password: 

production:
  <<: *common
  database: regulus_production
  username: production
  password: 
