common: &common
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost

development:
  <<: *common
  username: development
  password: 
  database: regulus_development

test:
  <<: *common
  username: test
  password: 
  database: regulus_test

production:
  <<: *common
  username: production
  password: 
  database: regulus_production
