# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6ba67f12d36c1fa77058fe9aa49e2a82fd980eae9f8fff47547f5a6365e7ab519a4f7603c34cc03ff1c8204fa745fbca526ed897f8de9572eb87fe985dde0f3

test:
  secret_key_base: 3e2514d7635dbfbb4bd4d127d1599adc9831860966b824758b9e0942ed7cffa241799a3a7eac75873612f6de153bbd979a312c9163908d368b24d40fd0c81896

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
