mysql:
  host: 'localhost'
  username: 'root'
  password: '7QiSlC?4'
  database: 'regulus'

rate:
  import:
    url: 'http://info.finance.yahoo.co.jp/fx/detail'
    pairs:
      - 'USDJPY'
      - 'EURJPY'
      - 'AUDJPY'
      - 'GBPJPY'
      - 'NZDJPY'
      - 'CADJPY'
      - 'CHFJPY'
      - 'ZARJPY'
      - 'CNHJPY'
      - 'EURUSD'
      - 'GBPUSD'
      - 'AUDUSD'
    out_of_service:
      from:
        hour: 20
        minute: 50
      to:
        hour: 22
        minute: 00
  aggregate:
    checker:
      min:
        - 5
        - 10
        - 20
        - 30
      hour:
        - 1
        - 2
        - 3
        - 4
        - 6
        - 12
      day:
        - 1
      month:
        - 1
  dump:
    backup_dir: 'backup/rates'
    header: 'time,pair,bid,ask'
  delete:
    period: 2
