mysql:
  host: 'localhost'
  username: 'root'
  password: '7QiSlC?4'
  database: 'regulus'

import:
  pairs:
    - 'AUDJPY'
    - 'CADJPY'
    - 'CHFJPY'
    - 'EURJPY'
    - 'GBPJPY'
    - 'NZDJPY'
    - 'USDJPY'
aggregate:
  checker:
    min:
      - 1
      - 5
      - 10
      - 15
      - 20
      - 30
    hour:
      - 1
      - 2
      - 3
      - 4
      - 6
      - 12
    day:
      - 1
    month:
      - 1
