pairs:
  - USDJPY
  - EURJPY
  - AUDJPY
  - GBPJPY
  - NZDJPY
  - CADJPY
  - CHFJPY
  - ZARJPY
  - CNHJPY
  - EURUSD
  - GBPUSD
  - AUDUSD

intervals:
  - 5-min
  - 10-min
  - 20-min
  - 30-min
  - 1-hour
  - 2-hour
  - 3-hour
  - 4-hour
  - 6-hour
  - 12-hour
  - 1-day
  - 1-week
  - 1-month
