default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  password:
  database: zosma

development:
  <<: *default
  username: development

test:
  <<: *default
  username: test
  database: zosma_test

production:
  <<: *default
  username: production
